import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const readSource = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8")

test("keeps production UI interaction contracts", async () => {
  const [buttons, inputs, admin, layout, shell, compare, product, auth, account, api] = await Promise.all([
    readSource("src/components/ui/button.tsx"),
    readSource("src/components/ui/input.tsx"),
    readSource("src/components/AdminApp.jsx"),
    readSource("src/layouts/BaseLayout.astro"),
    readSource("src/components/AppShell.jsx"),
    readSource("src/components/CompareApp.jsx"),
    readSource("src/components/ProductApp.jsx"),
    readSource("src/components/AuthApp.jsx"),
    readSource("src/components/MeApp.jsx"),
    readSource("src/lib/aprice-api.mjs"),
  ])

  assert.match(buttons, /default:\s*\n\s*"h-11[^"]*md:h-10/, "buttons need 44px mobile targets")
  assert.match(inputs, /"h-11[^"]*md:h-10/, "inputs need 44px mobile targets")
  assert.doesNotMatch(buttons, /md:h-[678]/, "desktop buttons must not shrink below usable targets")
  assert.doesNotMatch(inputs, /md:h-8/, "desktop inputs must not shrink below usable targets")
  assert.doesNotMatch(layout, /<div id="main-content"/, "the skip target must not wrap the site header")
  assert.match(shell, /<main id="main-content" tabIndex=\{-1\}>/)
  assert.match(compare, /<main id="main-content" tabIndex=\{-1\}>/)
  assert.match(compare, /env\(safe-area-inset-bottom\)/)
  assert.match(compare, /查询门店价/)
  assert.doesNotMatch(compare, /disabled=\{loading \|\| \(turnstileEnabled && !captchaToken\)\}/)
  assert.match(compare, /登录后将自动继续查询门店价格，当前比价清单不会丢失。/)
  assert.match(compare, /priceIntent=\{Boolean\(pendingPriceId\)\}/)
  assert.match(compare, /if \(!compareSource\) void recordTelemetryEvent\("compare_list_opened"/)
  assert.match(compare, /"price_query_succeeded" : "price_query_empty"/)
  assert.match(compare, /recordTelemetryEvent\("compare_completed"/)
  assert.match(compare, /fetchCommercialOffers\(selected\)/)
  assert.match(compare, /recordCommercialClick\(offer\.id, "compare"\)/)
  assert.match(compare, />合作购买<\/Button>/)
  assert.match(compare, /setSavedProducts\(\(items\) => items\.map/)
  assert.match(compare, /referrerPolicy="no-referrer"/)
  assert.match(compare, /inline-flex min-h-11 items-center/)
  assert.match(account, /比较商品 \{dataCompareIds\.length\}/)
  assert.match(product, /env\(safe-area-inset-bottom\)/)
  assert.match(product, /比最低多/)
  assert.match(product, />地图<\/a>/)
  assert.match(product, /mobile_recommendation/)
  assert.match(product, /主动查询才计入今日价格查询额度。/)
  assert.match(product, /免费额度已用完，本次查询消耗/)
  assert.match(product, /可通过补价任务获得积分。/)
  assert.match(product, /查看积分与任务/)
  assert.match(product, /\/me\/#price-tasks/)
  assert.match(product, /compare_source=product/)
  assert.match(product, /任务门店已预选；保存时会同时提交公共价格审核。/)
  assert.match(product, /补价任务已提交审核，审核通过后发放积分。/)
  assert.match(product, /recordTelemetryEvent\("favorite_revisited"/)
  assert.match(product, /recordTelemetryEvent\("task_submitted"/)
  assert.match(product, /fetchCommercialOffers\(\[productId\]\)/)
  assert.match(product, /recordCommercialClick\(commercialOffer\.id, "product"\)/)
  assert.match(product, /购买可能为 AAPRICE 带来收益/)
  assert.match(product, /id="record-price"/)
  assert.doesNotMatch(product, /await loadPrivate\(productId, activeSession, next\)/)
  assert.match(account, /task=1[\s\S]*#record-price/)
  assert.match(account, /fetchActivePriceTask\(\)/)
  assert.match(account, /recordTelemetryEvent\("task_claimed"/)
  assert.match(account, /fetchFavoritePriceChanges\(\{ days: 7 \}\)/)
  assert.match(account, /fetchMyPriceAlerts\(\)/)
  assert.match(account, /upsertPriceAlert/)
  assert.match(account, /降价提醒/)
  assert.match(account, /alertByProduct/)
  assert.match(account, /favoriteChangeByProduct/)
  assert.match(account, /新增报价/)
  assert.match(account, /近期无报价/)
  assert.match(account, /id="price-tasks"/)
  assert.match(account, /审核通过后获得 \{credit\?\.approved_contribution_reward/)
  assert.match(account, /有效期至 \{formatDate\(task\.expires_at, true\)\}/)
  assert.match(account, /Promise\.allSettled/)
  assert.match(account, /role="tablist"/)
  assert.match(await readSource(".github/workflows/deploy.yml"), /PUBLIC_DISABLE_TURNSTILE:.*\|\| '1'/)
  assert.match(auth, /subscribeAuthState[\s\S]*?\.catch\(\(error\) =>/)
  assert.doesNotMatch(auth, /请先完成人机验证。/)
  assert.doesNotMatch(auth, /disabled=\{loading \|\| \(turnstileEnabled/)
  assert.match(admin, /if \(await act\([\s\S]*?\)\) setProductForm\(blankProduct\)/)
  assert.match(admin, /if \(await act\([\s\S]*?\)\) setStoreForm\(blankStore\)/)
  assert.match(admin, /if \(await act\([\s\S]*?\)\) setPriceForm\(blankPrice\)/)
  assert.match(admin, /运营待办概览/)
  assert.match(admin, /纬度（-90～90）和经度（-180～180）/)
  assert.match(admin, /积分调整必须是非零整数，并填写原因/)
  assert.match(admin, /Promise\.allSettled/)
  assert.match(admin, /recordTelemetryEvent\("task_approved"/)
  assert.match(admin, /adminFetchCommercialOffers\(\)/)
  assert.match(admin, /adminUpsertCommercialOffer\(commercialForm\)/)
  assert.match(admin, /商业链接/)
  assert.match(admin, /商品覆盖目标/)
  assert.match(admin, /CommercialCoverageSummary/)
  assert.match(admin, /归因点击/)
  assert.match(admin, /toggleCommercialOffer/)
  assert.match(admin, /价格覆盖健康度/)
  assert.match(admin, /降价提醒发送健康度/)
  assert.match(admin, /adminFetchPriceAlertSummary\(\{ days: 7 \}\)/)
  assert.match(admin, /通知终止失败/)
  assert.match(admin, /会员功能决策门槛/)
  assert.match(admin, /adminFetchMembershipReadiness\(\{ days: 30 \}\)/)
  assert.match(admin, /可以进入方案设计/)
  assert.match(admin, /成交与佣金/)
  assert.match(admin, /adminFetchAffiliateReports\(\{ days: 180 \}\)/)
  assert.match(admin, /adminUpsertAffiliateReport/)
  assert.match(admin, /保存周期汇总/)
  assert.match(admin, /商业与供给漏斗/)
  assert.match(admin, /\[7, 30, 90\]\.map/)
  assert.match(admin, /changeTelemetryWindow/)
  assert.match(admin, /price_to_action_percent/)
  assert.match(admin, /task_claim_to_approval_percent/)
  assert.match(admin, /seven_day_return_percent/)
  assert.match(admin, /adminFetchPriceHealth\(\{ days: 30, limit: 20 \}\)/)
  assert.match(admin, /onOpenProduct=\{openProduct\}/)
  assert.match(api, /rpc\("admin_fetch_price_health", \{ payload \}/)
  assert.match(api, /rpc\("admin_fetch_price_alert_summary", \{ payload \}/)
  assert.match(api, /rpc\("admin_fetch_membership_readiness", \{ payload \}/)
  assert.match(api, /rpc\("admin_fetch_affiliate_reports", \{ payload \}/)
  assert.match(api, /rpc\("admin_upsert_affiliate_report", \{ payload \}/)
  assert.match(api, /admin_fetch_price_health\|PGRST202\|schema cache/)
  assert.match(api, /rpc\("record_commercial_click"/)
  assert.match(api, /commercial_outbound_clicked/)
  assert.match(api, /rpc\("admin_fetch_commercial_offers"/)
  assert.match(api, /rpc\("admin_upsert_commercial_offer"/)
  assert.match(api, /rpc\("fetch_favorite_price_changes"/)
  assert.match(api, /rpc\("fetch_my_price_alerts"/)
  assert.match(api, /rpc\("upsert_price_alert"/)
  assert.match(api, /try \{ sessionId = sessionStorage\.getItem/)
})

test("price alert worker keeps secrets server-side and records every outcome", async () => {
  const [worker, workflow, config] = await Promise.all([
    readSource("supabase/functions/send-price-alerts/index.ts"),
    readSource(".github/workflows/price-alerts.yml"),
    readSource("supabase/config.toml"),
  ])
  assert.match(worker, /PRICE_ALERT_CRON_SECRET/)
  assert.match(worker, /RESEND_API_KEY/)
  assert.match(worker, /rpc\("claim_price_alert_deliveries"/)
  assert.match(worker, /rpc\("complete_price_alert_delivery"/)
  assert.match(worker, /"idempotency-key": String\(delivery\.idempotency_key\)/)
  assert.match(worker, /"user-agent": "aaprice-price-alerts\/1\.0"/)
  assert.doesNotMatch(worker, /PUBLIC_/)
  assert.match(workflow, /cron: "\*\/15 \* \* \* \*"/)
  assert.match(workflow, /PRICE_ALERT_FUNCTION_URL/)
  assert.match(config, /\[functions\.send-price-alerts\][\s\S]*verify_jwt = false/)
  const deployWorkflow = await readSource(".github/workflows/deploy-functions.yml")
  assert.match(deployWorkflow, /supabase\/setup-cli@v1/)
  assert.match(deployWorkflow, /version: 2\.116\.0/)
  assert.match(deployWorkflow, /functions deploy send-price-alerts/)
})
