for(const u of ['https://www.mineiyakuhin.co.jp/','https://komeya-drug.com/','https://www.uchiyama-sasaki.com/']){try{const r=await fetch(u);const t=await r.text();console.log(u,r.status,t.length,(t.match(/google\.maps|LatLng|iframe/g)||[]).length,[...t.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store|店舗/i.test(x)).slice(0,8).join('|'))}catch(e){console.log(u,e.message)}}
const m=await(await fetch('https://www.mineiyakuhin.co.jp/store/')).text();console.log('MSTORE',m.length,(m.match(/店舗/g)||[]).length,(m.match(/google|LatLng|iframe/g)||[]).length);console.log([...m.matchAll(/href="([^"]+)"/g)].map(x=>x[1]).filter(x=>/store|shop/i.test(x)).slice(0,20).join('|'))
const k=await(await fetch('https://komeya-drug.com/store/')).text();console.log('KSTORE',k.length,(k.match(/店舗/g)||[]).length,(k.match(/LatLng|maps\/place|iframe/g)||[]).length)
await (await import('node:fs/promises')).writeFile('artifacts/komeya-store.html',k);console.log((k.match(/data-[a-z-]+="[^"]+"/g)||[]).slice(0,30).join('|'));console.log([...k.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/store|shop|map/i.test(x)).slice(0,30).join('|'))
const kd=await(await fetch('https://komeya-drug.com/store/%e3%82%b3%e3%83%a1%e3%83%a4%e8%96%ac%e5%b1%80%e6%b3%89%e5%ba%97/')).text();console.log('KDETAIL',kd.length,(kd.match(/maps|iframe|latitude|longitude/g)||[]).length)
const yy=await(await fetch('https://cosmetics-medical.com/storelocator/')).text();await (await import('node:fs/promises')).writeFile('artifacts/yamada-storelocator.html',yy);console.log('YAMADA',yy.length,(yy.match(/store_area|maps\/place|@35/g)||[]).length,[...yy.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/store|shop/i.test(x)).slice(-20).join('|'))
for(const [n,u] of [['nara','https://www.ms-drug.com/'],['nishi','https://www.nishiichi.com/'],['hikari','https://www.drug-hikari.co.jp/']]){try{const r=await fetch(u),t=await r.text();console.log(n,r.status,t.length,(t.match(/LatLng|maps\/place|data-lat|iframe/g)||[]).length)}catch(e){console.log(n,e.message)}}
const nr=await(await fetch('https://www.ms-drug.com/')).text();await (await import('node:fs/promises')).writeFile('artifacts/nara.html',nr);console.log([...nr.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store|店舗/i.test(x)).slice(0,20).join('|'))
const ns=await(await fetch('https://www.ms-drug.com/shop/index.html')).text();await (await import('node:fs/promises')).writeFile('artifacts/nara-shop.html',ns);console.log('NARASHOP',ns.length,(ns.match(/店舗/g)||[]).length,(ns.match(/google|maps|LatLng|iframe/g)||[]).length,[...ns.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store/i.test(x)).slice(0,30).join('|'))
const di=await(await fetch('https://www.kusu1.com/')).text();await (await import('node:fs/promises')).writeFile('artifacts/daiichi.html',di);console.log('DAIICHI',di.length,(di.match(/店舗/g)||[]).length,(di.match(/maps|LatLng|iframe|google/g)||[]).length,[...di.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store|店舗/i.test(x)).slice(0,20).join('|'))
const ds=await(await fetch('https://www.kusu1.com/shop.html')).text();await (await import('node:fs/promises')).writeFile('artifacts/daiichi-shop.html',ds);console.log('DSHOP',ds.length,(ds.match(/店舗/g)||[]).length,(ds.match(/maps|LatLng|iframe|google/g)||[]).length)
const w=await(await fetch('https://www.welpark.jp/shop/')).text();await (await import('node:fs/promises')).writeFile('artifacts/welpark.html',w);console.log('WEL',w.length,[...w.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store|tenpo/i.test(x)).slice(0,30).join('|'),(w.match(/json|api|ajax|iframe|google/g)||[]).slice(0,20).join('|'))
const mi=await(await fetch('https://www.miyamoto-drug.co.jp/')).text();await (await import('node:fs/promises')).writeFile('artifacts/miyamoto.html',mi);console.log('MIYAMOTO',mi.length,(mi.match(/maps|LatLng|iframe|店舗/g)||[]).length,[...mi.matchAll(/href="([^"]+)"/g)].map(m=>m[1]).filter(x=>/shop|store|店舗/i.test(x)).slice(0,20).join('|'))
const md=await(await fetch('https://www.miyamoto-drug.co.jp/store/ohyamahigashicho')).text();await (await import('node:fs/promises')).writeFile('artifacts/miyamoto-detail.html',md);console.log('MIYDETAIL',md.length,(md.match(/maps|LatLng|iframe|geo/g)||[]).length)
